server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  config:
    import: optional:secrets.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/supportportal?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    baseline-description: "init"
    baseline-version: 0

logging:
  level:
    root: debug
