server:
  port: 5000
  error:
    whitelabel:
      enabled: false

spring:
  config:
    import: optional:secrets-prod.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supportportal
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: debug
'


