server:
  port: 5000
  error:
    whitelabel:
      enabled: false

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: optional:secrets.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/supportportal?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      #dialect: org.hibernate.dialect.PostgreSQL81Dialect
  flyway:
    baseline-on-migrate: true
    validateOnMigrate: false
    enabled: true
    user: postgres
    password: ${DB_PASSWORD}
    baseline-description: "init"
    baseline-version: 0
jwt:
  secret: ${JWT_SECRET}
email:
  username: 'smalecbartlomiej@outlook.com'
  password: ${EMAIL_PASSWORD}

logging:
  level:
    root: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"



