spring:
  datasource:
    password: 4MlzHbraLZkPvhQ+8VYfueh?5ds
jwt:
  secret: 'FdMSpY6dNFlEF3zHVhhIkXEZ0udQCdyzQslxnO9n'
email:
  username: 'smalecbartlomiej@outlook.com'
  password: 'lWSh4xV4bPXoLps3E'