spring:
  datasource:
    password: postgres
  flyway:
    password: postgres
jwt:
  secret: 'FdMSpY6dNFlEF3zHVhhIkXEZ0udQCdyzQslxnO9n'
email:
  username: 'smalecbartlomiej@outlook.com'
  password: 'lWSh4xV4bPXoLps3E'
